[package]
name = "http-stub-server-rust"
version = "0.0.1"
authors = ["Robert Parsons <headexplodes@gmail.com>"]
description = "Generic HTTP Stub Server (Rust)"

[dependencies]
regex = "0.2"
log = "0.3"
log4rs = "0.7"
hyper = "0.11.0"
futures = "0.1.14"
serde_json = "1.0"
